#!/usr/bin/env node

/**
 * Build script to create browser-compatible version from index.js
 * Wraps the ES6 module in a UMD pattern for browser usage
 * Properly handles all exports (default and named)
 */

const fs = require('fs');
const path = require('path');

const sourceFile = path.join(__dirname, 'index.js');
const outputFile = path.join(__dirname, 'hugerte-checklist-plugin.browser.js');
const packageJson = require('./package.json');

// Read the source file
let sourceCode = fs.readFileSync(sourceFile, 'utf8');

// Extract named exports before removing them
const namedExports = [];
const exportRegex = /export\s+(function|const)\s+(\w+)/g;
let match;
while ((match = exportRegex.exec(sourceCode)) !== null) {
    namedExports.push(match[2]);
}

// Remove all ES6 export statements
// Handles: export default, export function, export const
sourceCode = sourceCode
    .replace(/export\s+default\s+\w+\s*$/gm, '')  // export default xxx
    .replace(/export\s+function\s+/g, 'function ')  // export function xxx
    .replace(/export\s+const\s+/g, 'const ')        // export const xxx
    .trim();

// Validate that exports were removed
if (sourceCode.includes('export ')) {
    console.error('❌ Error: Failed to remove all export statements from source code');
    process.exit(1);
}

// Build the return object with all exports
const exportsList = namedExports.length > 0
    ? namedExports.map(name => `        ${name}`).join(',\n')
    : '        checklistPlugin';

const returnStatement = namedExports.length > 0
    ? `    return {\n${exportsList},\n        checklistPlugin\n    };`
    : '    return checklistPlugin;';

// Wrap in UMD pattern
const umdWrapper = `/**
 * checklistPlugin - Browser version (UMD)
 * Provides checklist/checkbox functionality without using the paid TinyMCE plugin
 *
 * @version ${packageJson.version}
 * @author Frank Etoundi
 * @license MIT
 *
 * This is an automatically generated file compiled from index.js
 * DO NOT EDIT THIS FILE DIRECTLY - Edit index.js and run: npm run build:browser
 *
 * Source: https://github.com/etoundi1er/hugerte-checklist-plugin
 * Build: ${new Date().toISOString()}
 */
(function (root, factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD
        define([], factory);
    } else if (typeof module === 'object' && module.exports) {
        // Node/CommonJS
        module.exports = factory();
    } else {
        // Browser globals
        root.checklistPlugin = factory();
    }
}(typeof self !== 'undefined' ? self : this, function () {
    'use strict';

${sourceCode}

${returnStatement}
}));
`;

// Write the output file
fs.writeFileSync(outputFile, umdWrapper, 'utf8');

console.log('✅ Browser build created successfully!');
console.log(`   Source: ${sourceFile}`);
console.log(`   Output: ${outputFile}`);
if (namedExports.length > 0) {
    console.log(`   Exports: checklistPlugin, ${namedExports.join(', ')}`);
}
